name: CentOS Stream

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-centos:
    name: CentOS
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container: centos:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Prepare
        run: |
          sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
          sed -i "s|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g" /etc/yum.repos.d/CentOS-*
          dnf install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm -y
          /usr/bin/crb enable
          dnf install centos-release-stream -y
          dnf swap centos-{linux,stream}-repos -y
          dnf distro-sync -y
          dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y
          dnf update -y
          dnf install yum-utils -y
          dnf install git make cmake gcc gcc-c++ binutils glibc-devel valgrind autoconf libtool bison re2c automake libxml2-devel sudo libuv-devel which -y
      - name: Configure & build
        run: |
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON ..
            cmake --build .
      - name: Run tests
        run: |
            cd build
            ./test-defer
            ./test-exceptions
            ./test-cthread
            ./test-arena
            ./test-thrd_tls
            ./test-tls
