name: macOS
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    name: macOS
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v4
      - name: Setup
        run: |
          brew install cmake
      - name: Configure & build
        run: |
            mkdir build
            cd build
            cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON ..
            cmake --build .
      - name: Run test examples
        run: |
            cd build
